const objectPropertyNames = Object.getOwnPropertyNames(Object.prototype)
const arrayPropertyNames = Object.getOwnPropertyNames(Array.prototype)
const stringPropertyNames = Object.getOwnPropertyNames(String.prototype)
const numberPropertyNames = Object.getOwnPropertyNames(Number.prototype)
const booleanPropertyNames = Object.getOwnPropertyNames(Boolean.prototype)
const symbolPropertyNames = Object.getOwnPropertyNames(Symbol.prototype)
const mapPropertyNames = Object.getOwnPropertyNames(Map.prototype)
const setPropertyNames = Object.getOwnPropertyNames(Set.prototype)
const promisePropertyNames = Object.getOwnPropertyNames(Promise.prototype)
const datePropertyNames = Object.getOwnPropertyNames(Date.prototype)
const functionPropertyNames = Object.getOwnPropertyNames(Function.prototype)
const regexPropertyNames = Object.getOwnPropertyNames(RegExp.prototype)
const errorPropertyNames = Object.getOwnPropertyNames(Error.prototype)
const int8ArrayPropertyNames = Object.getOwnPropertyNames(Int8Array.prototype)

console.log('------object-------')
console.log(objectPropertyNames)
console.log('------array-----')
console.log(arrayPropertyNames)
console.log('------string------')
console.log(stringPropertyNames)
console.log('-------number------')
console.log(numberPropertyNames)
console.log('-------boolean-----')
console.log(booleanPropertyNames)
console.log('-------symbol------')
console.log(symbolPropertyNames)
console.log('-------map------')
console.log(mapPropertyNames)
console.log('-------set------')
console.log(setPropertyNames)
console.log('-------promise------')
console.log(promisePropertyNames)
console.log('-------date------')
console.log(datePropertyNames)
console.log('-------function------')
console.log(functionPropertyNames)
console.log('-------regex------')
console.log(regexPropertyNames)
console.log('-------error------')
console.log(errorPropertyNames)
console.log('-------int8Array------')
console.log(int8ArrayPropertyNames)
